services:
  - type: web
    plan: free
    name: PYRO-RENAME-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/TEAM-PYRO-BOTZ/PYRO-RENAME-BOT.git
    branch: main
    autoDeploy: True
    envVars:
      - key: BOT_TOKEN
        sync: 6359064136:AAFvOdaWRAH00lMROZCArt6jp5f8U6Fue0I
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: START_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: WEBHOOK
        sync: false
